### PR TITLE
Current position retrieval timeouts, updated example

### PR DESCRIPTION
**Pull request by ened**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bugfix & Features

### :arrow_heading_down: What is the current behavior?

The PR solves a few things, but it started with:
I noticed that my phone would never switch off the GPS antenna when retrieving the location. The root cause was that `geolocator` tried to fetch the position through Androids LocationManager class. My office has no GPS signal, therefore the call would run forever. I attached a timeout to the Dart future (which worked), but the location request would stay because the actual Task was not closed when the Dart Future was cancelled.
As a workaround, I added a timeout option to the getCurrentPosition call and extended the Android Location Task.

To test everything, a few other things were needed:
 - The example needed an additional page for the FusedLocationProvider on Android.
 - The previous implementation of getCurrentPosition would keep the task queue busy by having a `await` call in there, which I tried to avoid.

The PR should probably be split before continuing. Will put it through test.

#### RFC from the maintainer 

Looking back at the PR, I think the introduction of a internal `timeout` field (and the os Handler etc) may not be the best way.
I'd very much prefer to use Darts `.timeout` method on a Future. To use it successfully though, a bit of the task management has to be moved into the Dart side.
For comparison, this PR enables code like this:
``` dart
Geolocator()
  ..forceAndroidLocationManager = false
  ..getCurrentPosition(
    desiredAccuracy: LocationAccuracy.best,
    timeout: Duration(seconds: 5),
  ).then((position) {
    if (mounted) {
      setState(() => _currentPosition = position);
    }
  }).catchError((e) {
    //
  });
```

However, it would be a lot better if Dart could specify the timeout like so:

``` dart
Geolocator()
  ..forceAndroidLocationManager = false
  ..getCurrentPosition(
    desiredAccuracy: LocationAccuracy.best,
  ).timeout(Duration(seconds: 5)).then((position) {
    if (mounted) {
      setState(() => _currentPosition = position);
    }
  }).catchError((e) {
    //
  });
```

Using the below way would be better as the error is not library-defined ("just return null on timeout") and Dart could raise its `TimeoutException` properly. To make that work, the Geolocator API internally would fetch a `TaskID` first, then start a task with that task ID and install a `whenComplete` handler on the returned future to cancel the task.

This comes with another set of problems though - namely what should happen when the Dart side disappears completely (e.g. the UI/ Activity is killed), and the location provider still runs in the background.

### :new: What is the new behavior (if this is a feature change)?

Added `timeout` option to `getCurrentPosition` API.

### :boom: Does this PR introduce a breaking change?

No.

### :bug: Recommendations for testing

This will need to be tested indoors / outdoors in high GPS and no-GPS situations.

### :memo: Links to relevant issues/docs

#248 
#242 
#199 
#135 
#123 

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by mvanbeusekom** [comment]
@ened, first of all thanks again for your effort. Looking forward on this (big) improvement. 

I fully agree with you that we should try to stick to the Dart timeout implementation. I am not sure yet how we can make sure to tell Android to cancel listening for location updates when the Dart future times out but you seem to have an idea on that so maybe you can point me to some additional reading?

Regarding your question on what to do when the Dart side disappears completely, I would say we can allow users to pass in a cancellation token which that can trigger when the app is disappearing and gives us a little bit of time to cancel the request for a position. How do you feel about that?

**Comment by ened** [comment]
> I fully agree with you that we should try to stick to the Dart timeout implementation. I am not sure yet how we can make sure to tell Android to cancel listening for location updates when the Dart future times out but you seem to have an idea on that so maybe you can point me to some additional reading?

So the getCurrentLocation method (or any other non-stream way) would:
1. Ask the native portion to create a task ID & remember it.
1. Call the native portion and submit the task ID. Native part then puts the task in a hash table of some sort
1. When the task is done, native portion will clear the task
1. When the task times out OR when the task is done, Dart side will call native portion to clear the task using [`whenComplete`](https://api.dartlang.org/stable/2.1.0/dart-async/Future/whenComplete.html).
    - If the task is already done (& therefore cleared), then nothing need to be done
    - If the task is still running, it will now be cancelled
 
> Regarding your question on what to do when the Dart side disappears completely, I would say we can allow users to pass in a cancellation token which that can trigger when the app is disappearing and gives us a little bit of time to cancel the request for a position. How do you feel about that?

I'm not sure about cancellation tokens and I prefer to not add external APIs or management (*users to pass token* sounds like it). Anything developers have to manage is something we'd need to test, maintain, document.

Android we can receive install (`onViewDestroy`)[https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.ViewDestroyListener.html] for the moment) listener which should be enough for this use case.

Will continue thinking - and may submit further PR to prepare for the changes.

**Comment by ened** [comment]
@mvanbeusekom current implementation pushed, happy to hear your comments.

**Comment by ened** [comment]
Another thing we may want to show in the example project is how to cancel a location request. It should done by [cancelling a stream](https://dart.academy/how_cancel_future/).

**Comment by mvanbeusekom** [comment]
@ened I have reviewed the code and I really like the way you approached it. Up to here it looks really good and I don't have any remarks so far. The PR is still annotated with [WIP] so I haven't approved it yet.

Regarding your remark on extending the example project with an example on how to cancel a location request. I think that would be a good idea, but maybe in a separate PR if you don't mind. It would make it easier for me to review and keep things apart.

**Comment by ened** [comment]
hi @mvanbeusekom I have removed the WIP label and have shipped our production App with these changes for a few weeks now. I have confidence the code works, but at some point would like this project to have proper e2e testing as seen in flutter/plugins.

Perhaps a next version with this could be labelled as release candidate (or major version bump) to avoid breaking apps.

**Comment by ened** [comment]
As a side note, I think the project could benefit from some sort of CI / automatic build, test and code formatting checks. :-)

**Comment by mvanbeusekom** [comment]
> As a side note, I think the project could benefit from some sort of CI / automatic build, test and code formatting checks. :-)

We are using Bitrise to automatically build, test and analyze the code. Unfortunately the application on Bitrise is created as a "private" build instead of "public" which means you need to be invited in out team to be able to see the build results. We are in the process of correcting this, however Bitrise doesn't support simply updating the App from "private" to "public" so we basically need to delete the current configuration and create a new App as "public" and add the same config.

**Comment by mvanbeusekom** [comment]
@ened I have finished the conversion from a "Private" Bitrise project into a "Public" Bitrise project. This means you can now also see the results of the automated builds. 

Each PR will be checked automatically and links to the logs will be added to the PR. Because this PR is created before we added the Bitrise integration is doesn't have any checks (I will see if I can still add them).

**Comment by ened** [comment]
@mvanbeusekom saw it - but the error is not related to this PR. Will open a second PR to fix the analysis issues. Thx!

Do you run flutter test / flutter driver on bitrise as well?

**Comment by ened** [comment]
@mvanbeusekom turns out the analysis errors did come from my PR; now resolved and ready for review once again.

**Comment by audkar** [comment]
I have some concerns regarding these changes. (And geolocator's `Task` complexity overall). And they makes things even more complicated.

So this PR does two things: 
1. Tries to solve problem that `getCurrentPosition()` doesn't remove locationListener when `Future` is canceled.
2. Adds new feature to have timeout parameter.

## Problem nr1:
Because of Flutter `Feature` can't be canceled and Flutter IPC with native code doesn't allow serial calls it is quite hard to know when Androids locationListener should be removed.

I think correct way to solve this would be to drop current `getCurrentPosition()` implementation (which is based on `MethodChannel`) and reuse technique used for `getPositionStream()`.  `getPositionStream()` is implemented with `EventChannel`. So native plugin gets notified when no more subscribers left and can remove locationUpdateListener from location manager.

Under the hood API's `getCurrentPosition()` method can be like: 
```
CancelableOperation<Location> getCurrentPosition(args) {
  final streamController = StreamController<Location>();
  return CancelableOperation.fromFuture(Future(() {
    final locations = getLocationStream(args).take(1);
    locations.pipe(streamController.sink);
    return streamController.stream.first;
  }), onCancel: () {
    streamController.close();
  });
}
```
So all Geolocator plugin logic would be: 
- have single location BroadcastStream
- connect via StreamChannel
- on Android side add location listener when streamChannel has at least one subscriber
- remove location listener when streamChannel has no subscribers

## Problem nr2:
I see no point on implementing timeout feature in such complex way when it is possible to do smth like:
```
getLocationStream(args).take(1).timeout(duration);
```

**Comment by ened** [comment]
Hi @audkar thank you that's a great review and a great suggestion to improve it.

Will update the PR asap.

**Comment by arcturus** [comment]
Any plans to have this merged?

**Comment by mvanbeusekom** [comment]
I have added time out support based on streams in version 6.0.0 (which is currently available as release candidate)

**Pull request closed without merging**
