### PR TITLE
Expose google location accuracy setting

### PR DESCRIPTION
**Pull request by julianzur**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
It provides a new interface where users are able to check whether the "Google Location Accuracy" setting was enabled, when the Google Play Services are installed.

**How do you update the versions of the interdependent subpackages?**
To develop locally I changed the pubspec to work with path references.... 🤔 

### :arrow_heading_down: What is the current behavior?
Every time the location is queried and the setting is disabled, a popup is shown to the user. This can make apps unusabled.

### :new: What is the new behavior (if this is a feature change)?
Users can now check if the setting has been enabled or not and decided if they want to force the `AndroidLocationManager` based on the result.

### :boom: Does this PR introduce a breaking change?
No, it adds a new interface.

### :memo: Links to relevant issues/docs
Implements the suggestion from: https://github.com/Baseflow/flutter-geolocator/issues/667#issuecomment-779164266

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

**Review by fabiomcarneiro — APPROVED** [review]

**Comment by 7h30n3** [comment]
What's the current state of this PR.
Is it likely to be merged?

**Comment by blubearec** [comment]
Any news on this?

**Comment by julianzur** [comment]
I did not get any feedback so far. By now the branch is pretty out of sync with master.
We're currently working with a fork of this plugin... 
@mvanbeusekom is it worth updating this branch or is there no chance for this to ever get merged?

**Comment by mvanbeusekom** [comment]
Hi @julianzur,

The geolocator supports the `getLocationAccuracy()` method which will return the location accuracy information (either `reduced`  or `precise`). 

Platforms that don't support specific accuracy settings (Windows, Linux, Web but also Android without Google Play) will always return `precise`. 

I don't see how this PR would offer additional functionality over the already existing features. Please let me know if I am missing something.

**Comment by julianzur** [comment]
This PR is open for a year now and I didn't follow development of the plugin closely (as I said we're on our own fork). If this feature already made it into master branch, we can close this PR. :) 
I just followed up on it since two people asked for it - and I was assuming that means it's not there yet.

**Comment by mvanbeusekom** [comment]
Closing this PR in favor of already existing feature `getLocationAccuracy()`.

**Pull request closed without merging**
