### PR TITLE
Update Play Services Location

### PR DESCRIPTION
**Pull request by Zazo032**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Updates the Play Services Location library for Android

### :arrow_heading_down: What is the current behavior?

If you add 

### :new: What is the new behavior (if this is a feature change)?

App shouldn't crash

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

Import a plugin that also adds the Play Services Location library (`camerawesome: 1.2.0`)

### :memo: Links to relevant issues/docs

[androidx.core](https://stackoverflow.com/questions/74085319/class-was-expected-declaration-of-com-google-android-gms-location-fusedlocatio)

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

**Comment by Zazo032** [comment]
Just tested this in our app - it fixes the issue :)

**Comment by mvanbeusekom** [comment]
Thank you for this contribution. I have just published version 4.1.6 of the geolocator_android package to pub.dev and should now be available.

**Comment by Zazo032** [comment]
Thanks @mvanbeusekom for the fast response!

**Comment by christocracy** [comment]
I am getting a flood of support requests at my plugin [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation/issues/933) because of this change.

Bumping `play-services:location` version should not have been added to a major release (ie: `4.2.0`, *not* `4.1.7`).

Last October, Android [made a breaking change](https://developers.google.com/android/guides/releases#october_13_2022) to `play-services:location` in `v21`.

It is a *really big deal* to update one's `play-services:location` version to `v21+`.

Also, it's a good idea to expose a `playServicesLocationVersion` [`ext` variable](https://github.com/transistorsoft/flutter_background_geolocation/blob/7a1cb79a91db30bd8c3d075111fa0ca1615ff7a5/android/build.gradle#L57), allowing developers to control their desired version, rather than [hard-coding it](https://github.com/Baseflow/flutter-geolocator/blob/e60daab16c5568ee46ff3c8851b16167c3e412e9/geolocator_android/android/build.gradle#L40) within `build.gradle`.  This has been a very common practice in the *React Native* ecosystem for years.

Then developers can easily control their gradle dependency version in their root `android/build.gradle`, [like this](https://github.com/transistorsoft/flutter_background_geolocation/blob/7a1cb79a91db30bd8c3d075111fa0ca1615ff7a5/example/android/build.gradle#L7)

I *do* plan to soon release a version of my `flutter_background_geolocation` to support `v21` (it's not a difficult task), but it should be noted in your CHANGELOG here that it's a **⚠️ breaking change** in a *major* version bump.

**Comment by christocracy** [comment]
>Also, it's a good idea to expose a playServicesLocationVersion `ext` variable

For further recommendation on using `ext` vars for dependency versions, see *Android's* own developers docs:  [*"Configure Project-wide Properties"*](https://developer.android.com/studio/build#project_wide_properties)

Screenshot 2023-01-27 at 12 59 41 PM

**Comment by apalala-dev** [comment]
> I am getting a flood of support requests at my plugin [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation/issues/933) because of this change.
> 
> Bumping `play-services:location` version should have been added to a major release (ie: `4.2.0`, _not_ `4.1.7`).
> 
> Last October, Android [made a breaking change](https://developers.google.com/android/guides/releases#october_13_2022) to `play-services:location` in `v21`.
> 
> It is a _really big deal_ to update one's `play-services:location` version to `v21+`.
> 
> Also, it's a good idea to expose a `playServicesLocationVersion` [`ext` variable](https://github.com/transistorsoft/flutter_background_geolocation/blob/7a1cb79a91db30bd8c3d075111fa0ca1615ff7a5/android/build.gradle#L57), allowing developers to control their desired version, rather than [hard-coding it](https://github.com/Baseflow/flutter-geolocator/blob/e60daab16c5568ee46ff3c8851b16167c3e412e9/geolocator_android/android/build.gradle#L40) within `build.gradle`. This has been a very common practice in the _React Native_ ecosystem for years.
> 
> Then developers can easily control their gradle dependency version in their root `android/build.gradle`, [like this](https://github.com/transistorsoft/flutter_background_geolocation/blob/7a1cb79a91db30bd8c3d075111fa0ca1615ff7a5/example/android/build.gradle#L7)
> 
> I _do_ plan to soon release a version of my `flutter_background_geolocation` to support `v21` (it's not a difficult task), but it should be noted in your CHANGELOG here that it's a "**⚠️ breaking change**" in a _major_ version bump.

We used an hard-coded version for [camerawesome](https://github.com/Apparence-io/CamerAwesome), we didn't know there were such incompatibilities.
Sorry about that. 🙏
We'll use the same principle as you do with `ext` variables. 👍

**Comment by christocracy** [comment]
@apalala-dev Thanks very much!

I suggest you copy the strategy used in my *simpler* [background-fetch](https://github.com/transistorsoft/flutter_background_fetch/blob/master/android/build.gradle) plugin.

:warning: I use the variable `playServicesLocationVersion`.  It's important that we settle on the same `ext` variable name.

In your plugin's `android/build.gradle`:

### Step 1 &mdash; Define your plugin's desired dependency `DEFAULTS` [at the top](https://github.com/transistorsoft/flutter_background_fetch/blob/master/android/build.gradle#L4-L6):

```gradle
def DEFAULT_APP_COMPAT_VERSION                  = "1.4.1"
def DEFAULT_LIFE_CYCLE_RUNTIME_VERSION          = "2.4.1"
def DEFAULT_LIFE_CYCLE_EXTENSIONS_VERSION       = "2.2.0"
```

### Step 2 &mdash; create function [`safeExtGet`](https://github.com/transistorsoft/flutter_background_fetch/blob/master/android/build.gradle#L30-L32)

This function has been copied and reused throughout the *React Native* plugin-developer community *for years* -- view any *React Native* plugin and you're likely to find this same method:

```gradle
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
```

### Step 3 &mdash; Read your vars using `safeExtGet`

Within your `dependencies` block, [read and use your vars using `safeExtGet`](https://github.com/transistorsoft/flutter_background_fetch/blob/master/android/build.gradle#L47-L49):

```gradle
dependencies {
    def appCompatVersion = safeExtGet('appCompatVersion', safeExtGet('supportLibVersion', DEFAULT_APP_COMPAT_VERSION))
    def lifeCycleRuntimeVersion = safeExtGet('lifeCycleRuntimeVersion', DEFAULT_LIFE_CYCLE_RUNTIME_VERSION)
    def lifeCycleExtensionsVersion = safeExtGet('lifeCycleExtensionsVersion', DEFAULT_LIFE_CYCLE_EXTENSIONS_VERSION)

    implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '+')
    implementation "androidx.appcompat:appcompat:$appCompatVersion"

    // LifeCycleObserver
    implementation "androidx.lifecycle:lifecycle-runtime:$lifeCycleRuntimeVersion"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifeCycleExtensionsVersion"
}
```

### Step 4:  Document your plugin's `ext` vars that it's aware of:

In your `README` (or wherever you put your *Android Setup Guide*, instruct the user about configuring their `ext` vars in their root `android/build.gradle`:

# `android/build.gradle`

As an app grows in complexity and imports a variety of 3rd-party modules, it helps to provide some key "Global Gradle Configuration Properties" which all modules can align their requested dependency versions to. `camerawesome` is aware of these variables and will align itself to them when detected.

📂 `android/build.gradle`

```diff
buildscript {
    ext.kotlin_version = '1.3.72'               // or latest
+   ext {
+       compileSdkVersion   = 31                // or latest
+       targetSdkVersion    = 31                // or latest
+       appCompatVersion    = "1.4.2"           // or latest
+       playServicesLocationVersion = "21.0.1 // or latest
+   }
}
```

## `android/app/build.gradle`

In addition, you should take advantage of the *Global Configuration Properties* **yourself**, replacing hard-coded values in your `android/app/build.gradle` with references to these variables:

:open_file_folder: `android/app/build.gradle`:

In addition, you should take advantage of the *Global Configuration Properties* **yourself**, replacing hard-coded values in your `android/app/build.gradle` with references to these variables:

```diff
android {
+   compileSdkVersion rootProject.ext.compileSdkVersion
    .
    .
    .
    defaultConfig {
        .
        .
        .
+       targetSdkVersion rootProject.ext.targetSdkVersion
    }
}
```

**Pull request merged**
