### PR TITLE
Adds MSL Altitude Support

### PR DESCRIPTION
**Pull request by Wackymax**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Feature: Adds NMEA message support to position updates
Feature: Adds MSL altitude support

### :arrow_heading_down: What is the current behavior?

Altitude is reported as height above the ellipsoid but iOS reports altitude as height above the geoid. It's also not possible to get NMEA messages in the current version.

### :new: What is the new behavior (if this is a feature change)?

- Adds a new NMEA message listener in Android
- Adds 2 settings to the AndroidSettings file to allow the user to request NMEA messages and to request that altitude is reported as MSL
- Adds the NMEA message as a property on the location model.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

1. Test without NMEA messages
2. Test with NMEA messages enabled
3. Test with MSL altitude.

### :memo: Links to relevant issues/docs

Coses https://github.com/Baseflow/flutter-geolocator/issues/561, closes https://github.com/Baseflow/flutter-geolocator/pull/605, closes https://github.com/Baseflow/flutter-geolocator/pull/819, closes https://github.com/Baseflow/flutter-geolocator/pull/932

Should help with: https://github.com/Baseflow/flutter-geolocator/issues/987

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [X] I updated the relevant documentation.
- [X] I rebased onto current `master`.

### CODE REVIEW

**Comment by Wackymax** [comment]
@mvanbeusekom please let me know if you are happy with this solution. It should have a smaller impact on all the other platforms compared to the current PR's that are up for NMEA.

**Comment by mvanbeusekom** [comment]
Hi @Wackymax,

Thank you for the PR and taking an interest. 

The impact is indeed a lot smaller compared to the other implementations. However it will still expose a field in the `Position` class that is only used on Android.

Wouldn't it be better if we could add a separate Dart class (e.g. `NmeaClient` to the `geolocator_android` package and expose that to people would like to make use of it? The additional benefit would be that developers can listen to the position stream and NMEA streams separately.

This is also more in line with the plans Google has for their plugins. I started updating the platform specific implementations inline with issue flutter/flutter#94224. Since I have some time available I can pick this up and see if I can get this implemented today and tomorrow.

Please let me know how you feel?

**Comment by Wackymax** [comment]
Sounds good. If you want to have a separate stream then https://github.com/Baseflow/flutter-geolocator/pull/932 is probably a good candidate for you to work from. I think having the option of reporting altitude as MSL is still a good candidate case for this PR. What are your thoughts on keeping that in?

**Comment by Wackymax** [comment]
@mvanbeusekom I've rebased on the latest master containing your changes. I've split things up a bit as well, still have the MSL option for altitude in Android settings and I've created a separate channel for NMEA messages but I am not sure how to go about using it with the approach you want to take. Do you want to take it from here?

**Comment by Wackymax** [comment]
Closing this to bring in this changes with a new PR

**Comment by Wackymax** [comment]
Yeah I would be very lost 😅. I think it best for you to take over. Seems like you have a much better idea of how to approach this.

**Pull request closed without merging**
