### PR TITLE
Export AndroidResource class

### PR DESCRIPTION
**Pull request by tamizhgeek**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Export `AndroidResource` class from the `geolocator` and `geolocator_android` libraries to allow configuring the icon of the notifications

### :arrow_heading_down: What is the current behavior?
`AndroidResource` class is not exported, so there is no way to configure the `notificationIcon` of the `ForegroundNotificationConfig` class. 

### :new: What is the new behavior (if this is a feature change)?
Users can use the `AndroidResource` class to configure the `notificationIcon` of the `ForegroundNotificationConfig` class. 

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
NA

### :memo: Links to relevant issues/docs

https://github.com/Baseflow/flutter-geolocator/issues/1011

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

**Comment by tamizhgeek** [comment]
I'm not sure if I have to bump versions in both geolocator_android and geolocator packages. Let me know if should just bump one of them instead? Or maybe I should first create a PR for geolocator_android, get it merged and then create a new one for geolocator?

**Comment by mvanbeusekom** [comment]
Hi @tamizhgeek, 

Due to holiday I haven't been able to review this PR earlier. Best would be to split this PR up into 2 pull requests:

- First a PR updating the geolocator_android package (including a updated version number and changelog entry);
- Second (after the first is published) a PR updating the geolocator package.

Would you be able to help out to accomplish this?

**Comment by tamizhgeek** [comment]
Hey @mvanbeusekom thanks for the commend. Yes that sounds good to me. Will take care of it.

**Comment by ValentinTaleb** [comment]
Hey guys. Is there any plan to merge the fix?

Thank you very much in advance :)

**Comment by tamizhgeek** [comment]
Apologies for the delay @mvanbeusekom 

For now, it seems like the build is failing for reasons not related to the changes made in this PR. I will check back in a while and see if this is a temporary issue.

**Comment by tamizhgeek** [comment]
@mvanbeusekom all checks have passed now. I think this can be merged, please take a look.

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Please revert the changes to the `generated_plugins.cmake` file as it doesn't related to the topic this PR is trying to fix.

**Review by mvanbeusekom — APPROVED** [review]
LGTM

**Comment by mvanbeusekom** [comment]
Hi @tamizhgeek,

Thank you for all your work on this PR, I have just published the geolocator_android package containing this update to pub.dev (see https://pub.dev/packages/geolocator_android).

Would you mind creating the second PR to expose the `AndroidResource` through the `geolocator` package?

**Comment by tamizhgeek** [comment]
@mvanbeusekom Yes sure. Here it is: https://github.com/Baseflow/flutter-geolocator/pull/1136

**Pull request merged**
