### PR TITLE
Fix unsafe service cast

### LINKED ISSUE #1024: Fatal Exception: java.lang.ClassCastException
## 🐛 Bug Report
We're seeing crash reports due to [this unsafe cast](https://github.com/Baseflow/flutter-geolocator/blob/5f6e0aaae61c1178ebf93dfcaa80edef286de962/geolocator_android/android/src/main/java/com/baseflow/geolocator/GeolocatorPlugin.java#L40) lately

```
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.baseflow.geolocator.GeolocatorLocationService$a
       at com.baseflow.geolocator.GeolocatorPlugin$1.onServiceConnected(GeolocatorPlugin.java:9)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1979)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2011)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:245)
       at android.app.ActivityThread.main(ActivityThread.java:8024)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Configuration

**Version:** 8.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

### PR DESCRIPTION
**Pull request by markusrubey**
fixes #1024

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Hi @markusrubey,

Thank you for this fix. Would you mind updating the version in the pubspec.yaml and add an entry to the CHANGELOG.md so we can do a quick release?

**Comment by markusrubey** [comment]
Hey @mvanbeusekom,

thanks for your quick response. I bumped the version and added a changelog entry. Lemme know if that covers everything for a release 🙏

**Review by mvanbeusekom — APPROVED** [review]
LGTM! Thanks again, I will see to it that the update gets released today.

**Comment by onkarmonks** [comment]
@mvanbeusekom - Is this fix released. If yes can you please tell me the latest version for the library? The current seems to be 8.2.0 which is the old version

**Comment by mohanK22** [comment]
Hi @mvanbeusekom, is this issue fixed released?? please update us...

**Comment by mvanbeusekom** [comment]
@onkarmonks, @mohanK22, yes it has been released as part of geolocator_android version 3.1.5 (as mentioned in the CHANGELOG part of this PR).

If you only depend on the `geolocator` package make sure you run `flutter pub upgrade` so that Flutter can update all child dependencies (only minor and patch changes are updated, which is fine since this is a path change).

**Pull request merged**
