### PR TITLE
MSL Altitude on Android

### PR DESCRIPTION
**Pull request by Wackymax**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Feature

### :arrow_heading_down: What is the current behaviour?

Currently android reports location altitude as the value received from the GPS directly. 

### :new: What is the new behaviour (if this is a feature change)?

There are some use cases where MSL altitude is desired instead.  NMEA messages can used in these scenarios to get the MSL altitude for the location instead of the normal geoid altitude. This feature adds a new Android setting requesting the platform to report altitude as MSL instead which will then register and NMEA client on the Android side if available and use the NMEA messages instead as the altitude values for position updates.

### :boom: Does this PR introduce a breaking change?

No, the change is backwards compatible with existing clients.

### :bug: Recommendations for testing

Toggle the Android setting to use MSL or not to use MSL in the example app and observe the difference in altitude being reported

### :memo: Links to relevant issues/docs

https://github.com/Baseflow/flutter-geolocator/issues/987

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

**Comment by Wackymax** [comment]
@mvanbeusekom I know there are a few open PR's for NMEA but I figured I'd make this one to get MSL reporting in without changing any platform interfaces. This also allows Geolocator to mimic the Location package in behaviour which might be beneficial considering many peeps are migrating from that due to it's lack of support.

**Comment by Wackymax** [comment]
@mvanbeusekom did you get a change to look at the PR and the proposed change yet?

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Hi @Wackymax,

Sorry for the late reply. I have reviewed the suggested changes and look good to me. I just have one small remark regarding the version number (p.s. make sure to fetch the latest changes on the `main` branch to prevent merge conflicts).

**Comment by Wackymax** [comment]
@mvanbeusekom anything else that needs to be done?

**Comment by Wackymax** [comment]
Oh nice! Enjoy the holiday 😃

**Review by mvanbeusekom — APPROVED** [review]
LGTM, Thanks again for all the effort @Wackymax

**Pull request merged**
