### PR TITLE
Allow excluding Google mobile services

### LINKED ISSUE #841: No google services compile option
## 🚀 Feature Requests

I would like that at compile time, the plugin use pure Android location manager

### Contextualize the feature

To use this plugin on flutter apps that have to be published on Fdroid, I need to have an apk without any google location classes. 

### Describe the feature

I'm trying to find the way to do this, with the same code, just adding maybe a flutter build option, or something on gradle, to specify if Android location manager or both have to be added to the APK. 

I'm not sure if this is possible to be done, and how difficult can be. For the moment i have two versions, one including this plugin, and the other without. Witch is annoying. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

### PR DESCRIPTION
**Pull request by Robbendebiene**
This fixes a crash when the Google mobile services dependency is globally excluded.
Fixes #841(at least good enough in my opinion)

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

"feature" and docs update

### :arrow_heading_down: What is the current behavior?

Currently the app crashes when excluding GMS dependency.

```
E/AndroidRuntime(22305): FATAL EXCEPTION: main
E/AndroidRuntime(22305): Process: de.tu_chemnitz.etit.sse.openstop, PID: 22305
E/AndroidRuntime(22305): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
E/AndroidRuntime(22305):        at com.baseflow.geolocator.location.GeolocationManager.isGooglePlayServicesAvailable(GeolocationManager.java:77)
E/AndroidRuntime(22305):        at com.baseflow.geolocator.location.GeolocationManager.createLocationClient(GeolocationManager.java:71)
E/AndroidRuntime(22305):        at com.baseflow.geolocator.location.GeolocationManager.isLocationServiceEnabled(GeolocationManager.java:44)
E/AndroidRuntime(22305):        at com.baseflow.geolocator.MethodCallHandlerImpl.onIsLocationServiceEnabled(MethodCallHandlerImpl.java:138)
E/AndroidRuntime(22305):        at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
...
```

### :new: What is the new behavior (if this is a feature change)?

The `isGooglePlayServicesAvailable` now returns false when the GMS dependency is excluded, wherefore Geolocator will fallback to the Android LocationManager.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

Create a simple app that calls a method like `Geolocator.isLocationServiceEnabled()` or `Geolocator.getCurrentPosition()` and add the following to your `android/app/build.gradle` file:
```gradle
configurations.implementation {
   exclude group: 'com.google.android.gms'
}
```
The app should crash without the "fix" introduced in this PR.

### :memo: Links to relevant issues/docs

More infos about the gradle dependency exclusion: https://tomgregory.com/how-to-exclude-gradle-dependencies/

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Please let me know what you think, if you prefer any changes and if I should update the `pubspec.yaml` version.

**Comment by Robbendebiene** [comment]
Hi @mvanbeusekom I don't want to bug you in any way. Just in case this slipped under the radar I wanted to ask if you could review the PR?

**Review by mvanbeusekom — APPROVED** [review]
LGTM! Thank you very much for this contribution, very much appreciated.

**Comment by mvanbeusekom** [comment]
> Hi @mvanbeusekom I don't want to bug you in any way. Just in case this slipped under the radar I wanted to ask if you could review the PR?

Hi @Robbendebiene, no it didn't slip under the radar I just needed some time to get things in order. It seemed I was reviewing and testing the PR just when you send this message ;). 

The changes should have been published now as version 3.1.8, thanks again for this contribution.

**Comment by maxammann** [comment]
Looks got, in a previous project we managed to work around the crashing by forcing to use the legacy location manager on android. But this seems cleaner!

**Pull request merged**
