### PR TITLE
Migrate to v2 plugin api for android

### PR DESCRIPTION
**Pull request by Raphicci**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

This pull request aims to implement the migration to the v2 plugin api for Android as issued here:  #388  

### :arrow_heading_down: What is the current behavior?

On flutter channel master and dev, this plugin crashes at runtime on Android as it uses the old plugin now required (recommended on stable and beta channel)

### :new: What is the new behavior (if this is a feature change)?

V2 is working, the recommended message is gone. Retrocompatibility is also assured for V1 api.

### :boom: Does this PR introduce a breaking change?

The migration from V1 to V2 works automatically. This should not introduce breaking changes.

### :bug: Recommendations for testing

I have not tested this aside from the LocationUpdatesUsingLocation tasks.

### :memo: Links to relevant issues/docs

Migration follows guidelines from flutter docs : https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Raphicci** [comment]
I need juste a change in the example manifest and it will be good

**Comment by mvanbeusekom** [comment]
I will wait for that change before I merge it. Thanks again

**Comment by Raphicci** [comment]
Should be fine now. Thanks for the quick feedback. I'll probably get back to you for V2 api on flutter-google-api-availability.

**Comment by mvanbeusekom** [comment]
If you'd like you could also update the location_permissions plugin (which is also referenced by the Geolocator to handle the permissions part).

Otherwise I now have a good example on how to do it and will add it myself.

**Pull request merged**
